on: workflow_dispatch

name: AzureCLISampleForFile

permissions:
      id-token: write
      contents: read
jobs:

  build-and-deploy:
    runs-on: windows-latest  #ubuntu-latest
    #environment: dev
    steps:

    - name: Azure Login
      uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # - name: Checkout
    #   uses: actions/checkout@v1

    # - name: Azure CLI script file
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: 2.30.0
    #     inlineScript: |
    #       chmod +x $GITHUB_WORKSPACE/sampleScript.sh
    #       $GITHUB_WORKSPACE/sampleScript.sh
